version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: discount-app-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: discount-app-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d discount-app-db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
